### ISSUE TITLE
Update font style

### ISSUE THREAD

**Issue by n1kk0s** [n1kk0s/NewSuper322#2]
Font style should be updated to Azo Sans

**Comment by nadia39** [comment]
can i assist you on this issue and the other issue you have posted?
i am required to contribute to a open source project for a university module.
thanks

**Comment by n1kk0s** [comment]
Sure! For this we'll need to just make the fonts on the site Azo sans for now.

I've got a ton more issues that will be entered on Sunday regarding design changes and a few other things, so go ahead and fork it!

**Comment by nadia39** [comment]
I tried all night to change it, however I still can't grasp how to change the font on the website. I have the font you want in as a .OTF font folder right now

**Comment by n1kk0s** [comment]
You'll have to define a new font in the css file and set that as the font for the container class. Check out this link!

https://www.w3schools.com/css/css3_fonts.asp
